build_car:
  image: alpine
  script:
    - echo "Building the car"
    - mkdir build
    - cd build
    - touch car.txt
    - echo "Chassis" > car.txt
    - cat car.txt

test_car:
  image: alpine
  script:
    - test -f build/car.txt
    - grep "Chassis" car.txt